---
AWSTemplateFormatVersion: "2010-09-09"

Description: Setup ECS/Fargate cluster.

Parameters:
  ProjectName:
    Type: String

Resources:

  FargateCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Sub '${ProjectName}-fargate-cluster'
      CapacityProviders:
        #- FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        #- CapacityProvider: FARGATE
        #  Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

