name: 'Deploy CDK Stack'
description: 'checkout code, login to AWS, recover cdk cache and deploy cdk stacks'

inputs:
  stack-name:
    description: 'the CDK stack name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout source code and restore node cache
      uses: patternbox/you-build-it-you-run-it/.github/actions/prepare-node-cache@main
      with:
        working-directory: chatapp-infra

    - name: Cache CDK templates output
      uses: actions/cache@v4
      with:
        fail-on-cache-miss: true
        path: chatapp-infra/cdk.out
        key: ${{ runner.os }}-cache-cdk-out-${{ hashFiles('chatapp-infra/bin/**', 'chatapp-infra/lib/**', 'chatapp-infra/resources/**') }}

    - name: AWS login
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ env.TARGET_ACCOUNT_ID }}:role/${{ env.PROJECT_NAME }}-github-deployer
        role-duration-seconds: 900
        role-skip-session-tagging: true

    - name: Setup database stack
      shell: bash
      working-directory: chatapp-infra
      run: |
        npx cdk deploy ${{ inputs.stack-name }} --app 'cdk.out/' --require-approval never
