name: "22 --- [ Build Chatapp ]"

on:
  workflow_call:
    inputs:
      stage-env:
        type: string
        description: 'Staging environment (DEVELOP|PRODUCTION)'
        required: true

permissions:
  id-token: write
  contents: read

env:
  TARGET_ACCOUNT_ID: ${{ inputs[format('{0}_ACCOUNT_ID', inputs.stage-env)] || secrets[format('{0}_ACCOUNT_ID', inputs.stage-env)] }}

jobs:
  build-chatapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and apply dot-env file
        uses: patternbox/you-build-it-you-run-it/.github/actions/checkout-with-dotenv@main

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "16"

      - name: Cache Angular dist/** folder
        uses: actions/cache@v4
        id: cache-ui-dist
        with:
          path: chatapp-ui/dist
          key: ${{ runner.os }}-cache-ui-dist-${{ hashFiles('chatapp-ui/**') }}

      - name: Cache node modules (chatapp-infra)
        uses: actions/cache@v4
        env:
          package-lock-json: chatapp-infra/package-lock.json
        with:
          key: ${{ runner.os }}-build-chatapp-infra-${{ hashFiles( env.package-lock-json ) }}
          path: |
            ~/.npm
            chatapp-infra/node_modules

      - name: Cache node modules (chatapp-ui)
        uses: actions/cache@v4
        env:
          package-lock-json: chatapp-ui/package-lock.json
        with:
          key: ${{ runner.os }}-build-chatapp-ui-${{ hashFiles( env.package-lock-json ) }}
          path: |
            ~/.npm
            chatapp-ui/node_modules

      - name: Build Angular UI app
        working-directory: chatapp-ui
        if: ${{ steps.cache-ui-dist.outputs.cache-hit != 'true' }}
        run: |
          npm install -g @angular/cli@15.1.3
          ng build

      - name: Cache CDK templates output
        uses: actions/cache@v4
        id: cache-cdk-out
        with:
          path: chatapp-infra/cdk.out
          key: ${{ runner.os }}-cache-cdk-out-${{ hashFiles('chatapp-infra/bin/**', 'chatapp-infra/lib/**', 'chatapp-infra/resources/**') }}

      - name: Synthesize CDK code
        working-directory: chatapp-infra
        if: ${{ steps.cache-cdk-out.outputs.cache-hit != 'true' }}
        run: |
          ls -d ../chatapp-ui/*
          npx cdk synth
